project_id = "pupqzgvpmtsqnczifbrr"

[functions.convert-audio-to-mp3]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.admin-list-users]
verify_jwt = true

[functions.admin-bootstrap]
verify_jwt = false

[functions.admin-set-password]
verify_jwt = true

[functions.admin-get-user-email]
verify_jwt = true

[functions.admin-list-all-users]
verify_jwt = true
